config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
  post "/users/:user_id/posts/:id", to: "posts#update"

  resources :posts, only: :index do
    resources :comments, only: [:new, :create, :edit]
    resources :votes, only: [:create]
  end
  resources :comments, only: :index do
    resources :votes, only: [:create]
  end
  resources :users, except: :destroy do
    resources :posts, only: [:new, :create, :edit, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true

  belongs_to :user
  belongs_to :post
  has_many :votes, as: :votable
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :url, presence: true

  belongs_to :user
  has_many :comments
  has_many :votes, as: :votable
  after_initialize :set_defaults

  def set_defaults
    self.vote ||= 0
  end

end

app/models/user.rb
class User < ApplicationRecord
  validates :username, :email, :password, presence: true
  validates :username, uniqueness: true
  validates :password, length: {minimum: 6}
  has_secure_password
  before_validation { self.password_confirmation ||= password }

  has_many :posts
  has_many :comments
  has_many :votes
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :votable, polymorphic: true
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @comments = Comment.all
  end

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
    @comments = @post.comments
  end

  def create
      @post = Post.find(params[:post_id])
      @comment = current_user.comments.new(comment_params)
      @comment.post_id = params[:post_id]
      if @comment.save
        redirect_to "new"
      else
        @errors = @comment.errors.full_messages
        render "new"
      end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all.order(:vote)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.create(post_params)
    if @post == Post.last
      redirect_to root_url
    else
      @errors = @post.errors.full_messages
      render "new"
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to root_url
    else
      @errors = @post.errors.full_messages
      render "edit"
    end
  end

  def destroy
    Post.find(params[:id]).destroy
    flash[:success] = "Post Deleted"
    redirect_to root_url
  end

  private

    def post_params
      params.require(:post).permit(:title, :url, :user_idpos)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash[:danger] = "Login information is incorrect"
      render "new"
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Hacker News"
      redirect_to @user
    else
      @errors = @user.errors.full_messages
      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:username, :email, :password, :passwod_confirmation)
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def create
    if logged_in?
      post = Post.find(params[:post_id])
      user_vote = current_user.votes.where(votable_id: params[:post_id])
      if user_vote.length == 0
        vote = post.votes.create(votable_id: post.id, votable_type: post, user_id: current_user.id)
        redirect_to root_url
      else
        redirect_to root_url
      end
    else
      flash[:danger] = "Please login or create an accout to vote"
      redirect_to root_url
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def current_user?(user)
    user == current_user
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/views/comments/index.html.erb
<div class="container">
  <div class="row main-container">
    <div class="col-sm-12 col-md-12 col-lg-12 post-container">
      <%= render "shared/comments" %>
    </div>
  </div>
</div>

app/views/comments/new.html.erb
<div class="container">
  <div class="row main-container">
    <div class="col-sm-12 col-md-12 col-lg-12 post-container">
      <%= render "shared/post" %>
    </div>
  </div>
  <div class="row">
    <% if logged_in? %>
      <div class="col-sm-6 col-md-6 col-lg-6 form-container">
        <%= form_for(:comment, url: post_comments_path) do |f| %>
          <%= render "shared/error_messages" %>
            <div class="form-group">
              <%= f.text_area :body, :class => "form-control", size: "24x6" %>
            </div>
          <%= f.submit "Add a comment", :class => "btn btn-default" %>
        <% end %>
      </div>
    <% else %>
    <div class="col-sm-6 col-md-6 col-lg-6 form-container">
      <h3>Please login or create an account to leave a comment</h3>
    </div>
    <% end %>
  </div>
  <div class="row main-container">
    <div class="col-sm-12 col-md-12 col-lg-12 post-container">
      <%= render "shared/comments" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HackerNewsNick</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Dosis:300,400" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="container header">
      <header class="logo">
        <h1> <%= link_to('Hacker News', root_path)%></h1>
      </header>
      <nav>
        <ul class="nav-bar">
          <li> <%= link_to('comments', comments_path) %></li>
          <% if logged_in? %>
            <li> <%= link_to "submit", new_user_post_path(current_user) %> </li>
            <li> <%= link_to(current_user.username, current_user) %> </li>
            <li> <%= link_to('Logout', logout_path)%> </li>
          <% else %>
            <li> <%= link_to('create account', new_user_path)%> </li>
            <li> <%= link_to('login', login_path)%> </li>
          <% end %>
        </ul>
      </nav>
    </div>
    <div> <%= render "shared/show" %> </div>
    <%= yield %>
  </body>
  <footer></footer>
</html>

app/views/posts/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
      <h2>Edit</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6 col-md-6 col-lg-6 form-container">
      <%= form_for(:post, url: user_post_path) do |f| %>
        <%= render "shared/error_messages" %>
          <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, :class => "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :url %>
            <%= f.text_field :url, :class => "form-control" %>
          </div>
        <%= f.submit "Submit", :class => "btn btn-default" %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container main-container">
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12 post-container">
      <%= render "shared/posts" %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
      <h2>Submit</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6 col-md-6 col-lg-6 form-container">
      <%= form_for(:post, url: user_posts_path) do |f| %>
        <%= render "shared/error_messages" %>
          <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, :class => "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :url %>
            <%= f.text_field :url, :class => "form-control" %>
          </div>
        <%= f.submit "Submit", :class => "btn btn-default" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_comments.html.erb
<% @comments.each do |comment| %>
  <article class="comment">
   <span class="comment_upvote"> <%= "\u21EA" %> </span>
   <span class="date_author"> <%=  comment.user.username %> <%= comment.created_at.strftime("%H") %> hours ago </span>
    <p class="comment_body"> <%= comment.body %> </p>
  </article>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @errors %>
  <ul>
    <% @errors.each do |error| %>
      <li class="errors" ><%= error %></li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_post.html.erb
<article class="post">
 <h3 class="post_title"> <%= link_to(@post.title, @post.url) %> </h3>
 <span class="upvote"> <%= link_to("\u21EA", post_votes_path(@post)) %> </span>
 <span class="date_author"> <%= @post.votes.count %> points by <%= @post.user.username %> <%= @post.created_at.strftime("%H") %> hours ago | </span> <span> <%= @post.comments.count %> <%= link_to("comments", new_post_comment_path(@post)) %> </span>
  <% if current_user?(@post.user) %>
    <%= link_to "Edit", edit_user_post_path(@post, @post), :class => "btn btn-default edit-button" %>
    <%= link_to "Delete", user_post_path(@post, @post), method: :delete, :class => "btn btn-default edit-button" %>
  <% end %>
</article>

app/views/shared/_posts.html.erb
<% @posts.each do |post| %>
  <article class="post">
   <h3 class="post_title"> <%= link_to(post.title, post.url) %> </h3>
   <span class="upvote"> <%= link_to("\u21EA", post_votes_path(post), method: :post) %> </span>
    <span class="date_author"> <%= post.votes.count %> points by <%= post.user.username %> <%= post.created_at.strftime("%H") %> hours ago | </span> <span> <%= post.comments.count %> <%= link_to("comments", new_post_comment_path(post)) %> </span>
    <% if current_user?(post.user) %>
      <%= link_to "Edit", edit_user_post_path(post, post), :class => "btn btn-default edit-button" %>
      <%= link_to "Delete", user_post_path(post, post), method: :delete, :class => "btn btn-default edit-button" %>
    <% end %>
  </article>
<% end %>

app/views/shared/_show.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %> flash-alerts text-center"><%= message %></div>
<% end %>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-md-6 col-lg-6 form-container">
      <h2>Sign Up</h2>
      <%= form_for(@user) do |f| %>
        <%= render "shared/error_messages" %>
        <div class="form-group">
          <%= f.label :username %>
          <%= f.text_field :username, :class => "form-control"%>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, :class => "form-control"%>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, :class => "form-control"%>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation, "Confirmation" %>
          <%= f.password_field :password_confirmation, :class => "form-control"%>
        </div>
        <%= f.submit "Create my account", :class => "btn btn-default" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12 form-container">
      <h2>Welcome</h2>
      <p class = "profile">user: <%= @user.username %> </p>
      <p class = "profile">created: <%= @user.created_at.strftime("%H") %> hours ago</p>
      <p class = "profile">email: <%= @user.email %> </p>
    </div>
  </div>
  <h2>Your Stories</h2>
  <div class="row main-container">
    <div class="col-sm-12 col-md-12 col-lg-12 post-container">
        <%= render "shared/posts" %>
    </div>
  </div>
</div>